version: '3.9'

services:
  jmeterportalapi:
    image: dockerjmeterapi
    build:
      context: .
      dockerfile: JmeterPortalAPI/Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - db
  db:
      build: 
        context: .
        dockerfile: JmeterPortalDatabase/Dockerfile

