version: "3.8"
services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "IGVch123PX"
    ports:
      - "14331:1433"
  employeeapi:
    build:
      context: .
      dockerfile: ./JmeterPortalAPI/Dockerfile
    depends_on:
      - db
    ports:
      - "5555:80"
